---
version: '3'
services:
  ff-player-logger:
    image: filebrowser/filebrowser
    container_name: ff-player-logger
    user: 1000:1000
    ports:
      - 8866:8866
    volumes:
      - /home/bob/Documents/ffplayerlogger/:/usr/src/website/
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
